version: "3"

services:  
  mysql-ds:
    image: mysql:latest
    container_name: mysql-ds
    hostname: mysql-ds
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD=Mysqlroot123@
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - dfp_net
networks:
  dfp_net:
    external: true
