version: "3"

services:
  postgres-ds:
    image: postgres:15
    container_name: postgres-ds
    hostname: postgres-ds
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123@
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dfp_net
  
  mysql-ds:
    image: mysql:latest
    container_name: mysql-ds
    hostname: mysql-ds
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD=Mysqlroot123@
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - dfp_net
networks:
  dfp_net:
    external: true
